### ISSUE TITLE
Exception when using brainflow with Java 11

### ISSUE THREAD

**Issue by michaelgrj** [OpenBCI/brainflow#153]
I am not really sure what's the issue here because I am just getting started with OpenBCI and brainflow but I tried to use the library with Java and got an exception.

`Exception in thread "main" java.lang.NoClassDefFoundError: java/sql/Time
	at brainflow.jar.with.dependencies/com.google.gson.Gson.<init>(Gson.java:250)
	at brainflow.jar.with.dependencies/com.google.gson.Gson.<init>(Gson.java:186)
	at brainflow.jar.with.dependencies/brainflow.BrainFlowInputParams.to_json(BrainFlowInputParams.java:31)
	at brainflow.jar.with.dependencies/brainflow.BoardShim.<init>(BoardShim.java:509)
	at org.example/org.example.BoardTest.main(BoardTest.java:19)
Caused by: java.lang.ClassNotFoundException: java.sql.Time
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more`

I am using JDK 11 and Intellij to build the project.
I have an OpenBCI Cyton board but I don't think it has anything to do with the error I am getting. To use the library I have downloaded the jar file from the release section on GitHub. I used the brainflow-jar-with-dependencies file.
I hope I gave all the necessary information, Michael.

**Comment by Andrey1994** [comment]
We build it using jdk8 there is a known issue with running gson on java >= 9 which comes from java 9 modules. To fix it you need to add java module for sql. 

Relevant issue https://stackoverflow.com/questions/50877484/java-sql-time-exception 

I have an example here(you dont need javafx modules):
https://github.com/brainflow-dev/braindoro/blob/master/src/main/java/module-info.java#L10

**Comment by michaelgrj** [comment]
Thanks, that solved it. And also, if I may ask why are you not publishing your project on maven central?

**Comment by Andrey1994** [comment]
I wanna publish it there(from upstream version, not from fork) but I dont want to publish it manually for each version, so we will need to update CI pipelines...
