### ISSUE TITLE
brainflow.BrainFlowError: Error in prepare_session:BOARD_NOT_READY_ERROR

### ISSUE THREAD

**Issue by sieuwe1** [OpenBCI/brainflow#166]
I am having an issue getting my cython board to work with the OpenBCI gui. 

It connects fine as seen in the picture below. 

![Screenshot from 2021-04-13 23-26-34](https://user-images.githubusercontent.com/5994718/114625002-e4668300-9cb1-11eb-93a6-a0b0cf159cca.png)

However when I want to start a session I get this error:
```

-------------------------------------------------
ControlPanel: Attempting to Auto-Connect to Cyton
-------------------------------------------------

ControlPanel: Found Cyton Dongle on COM port: /dev/ttyUSB0
Success: Host and Device on Channel number: 20 using COM port: /dev/ttyUSB0
[DEFAULT]: Attempting to Start Session...
initButtonPressed: Calling initSystem() after next draw()
OpenBCI_GUI: Start session. Calling initSystem().


=================================================
||             INITIALIZING SYSTEM             ||
=================================================

[ERROR]: ERROR: brainflow.BrainFlowError: Error in prepare_session:BOARD_NOT_READY_ERROR when initializing Brainflow board. Data will not stream.
brainflow.BrainFlowError: Error in prepare_session:BOARD_NOT_READY_ERROR
	at brainflow.BoardShim.prepare_session(BoardShim.java:598)
	at OpenBCI_GUI$BoardBrainFlow.initializeInternal(OpenBCI_GUI.java:2459)
	at OpenBCI_GUI$BoardCyton.initializeInternal(OpenBCI_GUI.java:2985)
	at OpenBCI_GUI$Board.initialize(OpenBCI_GUI.java:1990)
	at OpenBCI_GUI.initSystem(OpenBCI_GUI.java:681)
	at OpenBCI_GUI.systemInitSession(OpenBCI_GUI.java:982)
	at OpenBCI_GUI.draw(OpenBCI_GUI.java:559)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Channel count set to 8
openBCI_GUI: haltSystem: Halting system for reconfiguration of settings...
[DEFAULT]: Data stream is already stopped.
[ERROR]: Failed to initialize board. Please check that the board is on and has power. See Console Log for more details.
OpenBCI_GUI::Control Panel: Playback history file not found.

```

I have not done anything to the firmware and the switches are set correctly. 

When using the python library of brainflow I get this error:
```

	[2021-04-13 23:45:57.577] [board_logger] [info] incoming json: {
    "file": "",
    "ip_address": "",
    "ip_port": 0,
    "ip_protocol": 0,
    "mac_address": "",
    "other_info": "",
    "serial_number": "",
    "serial_port": "/dev/ttyUSB0",
    "timeout": 0
}
[2021-04-13 23:45:57.577] [board_logger] [info] openning port /dev/ttyUSB0
[2021-04-13 23:46:03.724] [board_logger] [error] board doesnt send welcome characters!
Traceback (most recent call last):
  File "training_gui.py", line 78, in <module>
    eeg_headset.connect_to_headset("/dev/ttyUSB0")
  File "/home/sieuwe/Desktop/Fontys/Semester_5/Open-BCI-Drone-Control/board.py", line 18, in connect_to_headset
    board.prepare_session()
  File "/usr/local/lib/python3.6/dist-packages/brainflow/board_shim.py", line 882, in prepare_session
    raise BrainFlowError('unable to prepare streaming session', res)
brainflow.board_shim.BrainFlowError: BOARD_NOT_READY_ERROR:7 unable to prepare streaming session

```

Somehow the board is connecting but not wanting to start a session. 

What could be the problem?

Thanks

Sieuwe

**Comment by Andrey1994** [comment]
answered in slack, it looks like a problem with device
